ration:
  var: ration
  title: Current Ration
  description: Your current ration
  value: 1
  hidden: true

height:
  var: height
  title: Height
  description: You height in sm
  value: 180
  hidden: false

weight:
  var: weight
  title: Weight
  description: Your weight in kg
  value: 80
  hidden: false

proteins:
  var: proteins
  title: Proteins
  description: Proteins per day in grams (2g per kg)
  value: 160.0
  hidden: false

fats:
  var: fats
  title: Fats
  description: Fats per day in grams (0.5g per kg)
  value: 40.0
  hidden: false

carbs:
  var: carbs
  title: Carbohydrates
  description: Carbs per day in grams (4g per kg)
  value: 320.0
  hidden: false

meals:
  var: meals
  title: Meals
  description: Number of meals per day
  value: 4
  hidden: true

breakfast_time:
  var: breakfast_time
  title: "Breakfast time"
  description: Time your first meal start
  value: "8:00"
  hidden: false
